from fastapi import FastAPI                        # FastAPI class — creates the web application and registers all routes
from fastapi.concurrency import run_in_threadpool  # wraps a blocking (sync) function so it runs on a thread pool without blocking the async event loop
from pydantic import BaseModel                     # BaseModel — defines the shape of JSON request bodies with automatic validation
from agent import run_agent                        # our LangGraph pipeline — this is the only function the API needs to call

app = FastAPI(title="Rivalyze API")  # the app instance — every route decorator (@app.get, @app.post) attaches to this object


# ── Block 2: Request and Response Models ─────────────────────────────────────
# Pydantic models define the exact shape of JSON that goes IN and comes OUT of
# the API. FastAPI reads these classes and automatically:
#   1. Parses the incoming JSON body into the correct Python types
#   2. Returns a 422 error with a clear message if a field is missing or wrong type
#   3. Generates the /docs page (Swagger UI) so you can test the API in a browser

class ReportRequest(BaseModel):          # describes the JSON body a caller must send to trigger a report
    company_a: str                       # name of the first company — required, no default
    company_b: str                       # name of the second company — required, no default
    days_back: int = 90                  # how far back Tavily searches; defaults to 90 so callers can omit it


class ReportResponse(BaseModel):         # describes the JSON body the API sends back after the report is ready
    company_a: str                       # echoed back so the caller knows which company this report is about
    company_b: str                       # echoed back for the same reason — useful when handling multiple requests
    report: str                          # the full markdown report text generated by the LLM
    sources: list                        # list of dicts, each with "title" and "url", collected during Tavily search


# ── Block 3: POST /report Endpoint ───────────────────────────────────────────
# This is the single route the API exposes. A caller sends a POST request with
# a JSON body matching ReportRequest and gets back a JSON body matching ReportResponse.

@app.post("/report", response_model=ReportResponse)  # registers this function as the handler for POST /report; response_model tells FastAPI how to serialize the return value
async def generate_report(request: ReportRequest):   # async lets the server handle other requests while waiting; FastAPI injects the parsed request body here automatically
    result = await run_in_threadpool(                # run_agent is synchronous (blocking); run_in_threadpool moves it off the async event loop so the server stays responsive
        run_agent,                                   # the LangGraph pipeline function imported from agent.py
        request.company_a,                           # first company name, taken directly from the validated request body
        request.company_b,                           # second company name, taken directly from the validated request body
        request.days_back,                           # search window in days, taken directly from the validated request body
    )
    return ReportResponse(                           # construct the response object — Pydantic validates types, FastAPI serialises it to JSON automatically
        company_a=request.company_a,                 # echo the input company name so the caller can match response to request
        company_b=request.company_b,                 # echo the input company name for the same reason
        report=result["report"],                     # the markdown report string produced by the generate_report node in the graph
        sources=result["sources"],                   # list of {"title": ..., "url": ...} dicts collected by the two search nodes
    )


# ── Block 4: Health Check Endpoint ───────────────────────────────────────────
# A lightweight GET route that returns immediately with no work.
# Used by load balancers, Docker, and monitoring tools to confirm the server is up.
# Hitting POST /report to check liveness would be wasteful — this costs nothing.

@app.get("/health")               # registers this function as the handler for GET /health; no response_model needed — a plain dict is fine
def health():                     # regular (sync) function is fine here — no blocking I/O, so no need for async or run_in_threadpool
    return {"status": "Rivalyze API is running"}  # plain dict — FastAPI serialises it to JSON automatically; the value is a human-readable string for quick visual confirmation
